language: cpp

sudo: required

services:
  - docker

branches:
  only:
  - master
  - alexis/docker

install:
  - cd Docker
  - docker build -t "$DOCKER_USERNAME"/amanzi:latest -f Dockerfile-Amanzi .

script:
  - docker run --name test --workdir /home/amanzi_user/amanzi_builddir/amanzi "$DOCKER_USERNAME"/amanzi:latest  make test

after_success:
  - if [[ ${DOCKERHUB} == TRUE && ${DOCKER_USERNAME} && ${DOCKER_PASSWORD} && ${DEPLOY} ]]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" || travis_terminate 1;
      docker push "$DOCKER_USERNAME"/amanzi || travis_terminate 1;
    fi
